cb_newage_panel_create:
    type: entity
    class: CBNewAgeBundle:Panel
    permission: CREATE
    group_name: ""
    bindings: ~

cb_newage_panel_view:
    type: entity
    class: CBNewAgeBundle:Panel
    permission: VIEW
    group_name: ""
    bindings: ~

cb_newage_panel_update:
    type: entity
    class: CBNewAgeBundle:Panel
    permission: EDIT
    group_name: ""
    bindings: ~

cb_newage_panel_delete:
    type: entity
    class: CBNewAgeBundle:Panel
    permission: DELETE
    group_name: ""
    bindings: ~

cb_newage_panel_view_create:
    type: entity
    class: CBNewAgeBundle:PanelView
    permission: CREATE
    group_name: ""
    bindings: ~

cb_newage_panel_view_view:
    type: entity
    class: CBNewAgeBundle:PanelView
    permission: VIEW
    group_name: ""
    bindings: ~

cb_newage_panel_view_update:
    type: entity
    class: CBNewAgeBundle:PanelView
    permission: EDIT
    group_name: ""
    bindings: ~

cb_newage_panel_view_delete:
    type: entity
    class: CBNewAgeBundle:PanelView
    permission: DELETE
    group_name: ""
    bindings: ~

cb_newage_campaign_create:
    type: entity
    class: CBNewAgeBundle:Campaign
    permission: CREATE
    group_name: ""
    bindings: ~

cb_newage_campaign_view:
    type: entity
    class: CBNewAgeBundle:Campaign
    permission: VIEW
    group_name: ""
    bindings: ~

cb_newage_campaign_update:
    type: entity
    class: CBNewAgeBundle:Campaign
    permission: EDIT
    group_name: ""
    bindings: ~

cb_newage_campaign_delete:
    type: entity
    class: CBNewAgeBundle:Campaign
    permission: DELETE
    group_name: ""
    bindings: ~

cb_newage_support_type_create:
    type: entity
    class: CBNewAgeBundle:SupportType
    permission: CREATE
    group_name: ""
    bindings: ~

cb_newage_support_type_view:
    type: entity
    class: CBNewAgeBundle:SupportType
    permission: VIEW
    group_name: ""
    bindings: ~

cb_newage_support_type_update:
    type: entity
    class: CBNewAgeBundle:SupportType
    permission: EDIT
    group_name: ""
    bindings: ~

cb_newage_support_type_delete:
    type: entity
    class: CBNewAgeBundle:SupportType
    permission: DELETE
    group_name: ""
    bindings: ~

cb_newage_lighting_type_create:
    type: entity
    class: CBNewAgeBundle:LightingType
    permission: CREATE
    group_name: ""
    bindings: ~

cb_newage_lighting_type_view:
    type: entity
    class: CBNewAgeBundle:LightingType
    permission: VIEW
    group_name: ""
    bindings: ~

cb_newage_lighting_type_update:
    type: entity
    class: CBNewAgeBundle:LightingType
    permission: EDIT
    group_name: ""
    bindings: ~

cb_newage_lighting_type_delete:
    type: entity
    class: CBNewAgeBundle:LightingType
    permission: DELETE
    group_name: ""
    bindings: ~