parameters:
    cb_newage_panel.form.type.entity.class:                      CB\Bundle\NewAgeBundle\Form\Type\PanelType
    cb_newage_panel.form.type.entity.api.class:                  CB\Bundle\NewAgeBundle\Form\Type\PanelApiType
    cb_newage_panel.form.handler.entity.class:                   CB\Bundle\NewAgeBundle\Form\Handler\PanelHandler

    cb_newage_panel_view.form.type.entity.class:                      CB\Bundle\NewAgeBundle\Form\Type\PanelViewType
    cb_newage_panel_view.form.type.entity.api.class:                  CB\Bundle\NewAgeBundle\Form\Type\PanelViewApiType
    cb_newage_panel_view.form.handler.entity.class:                   CB\Bundle\NewAgeBundle\Form\Handler\PanelViewHandler

    cb_newage_campaign.form.type.entity.class:                      CB\Bundle\NewAgeBundle\Form\Type\CampaignType
    cb_newage_campaign.form.type.entity.api.class:                  CB\Bundle\NewAgeBundle\Form\Type\CampaignApiType
    cb_newage_campaign.form.handler.entity.class:                   CB\Bundle\NewAgeBundle\Form\Handler\CampaignHandler

    cb_newage_support_type.form.type.entity.class:                      CB\Bundle\NewAgeBundle\Form\Type\SupportTypeType
    cb_newage_support_type.form.type.entity.api.class:                  CB\Bundle\NewAgeBundle\Form\Type\SupportTypeApiType
    cb_newage_support_type.form.handler.entity.class:                   CB\Bundle\NewAgeBundle\Form\Handler\SupportTypeHandler

    cb_newage_lighting_type.form.type.entity.class:                      CB\Bundle\NewAgeBundle\Form\Type\LightingTypeType
    cb_newage_lighting_type.form.type.entity.api.class:                  CB\Bundle\NewAgeBundle\Form\Type\LightingTypeApiType
    cb_newage_lighting_type.form.handler.entity.class:                   CB\Bundle\NewAgeBundle\Form\Handler\LightingTypeHandler

    cb_newage_panel_address_collection.form.type.entity.class:          CB\Bundle\NewAgeBundle\Form\Type\PanelAddressCollectionType

    cb_newage_city.form.type.entity.class:                      CB\Bundle\NewAgeBundle\Form\Type\CityType
    cb_newage_city.form.type.entity.api.class:                  CB\Bundle\NewAgeBundle\Form\Type\CityApiType
    cb_newage_city.form.handler.entity.class:                   CB\Bundle\NewAgeBundle\Form\Handler\CityHandler

    cb_newage_offer.form.type.entity.class:                      CB\Bundle\NewAgeBundle\Form\Type\OfferType
    cb_newage_offer.form.type.entity.api.class:                  CB\Bundle\NewAgeBundle\Form\Type\OfferApiType
    cb_newage_offer.form.handler.entity.class:                   CB\Bundle\NewAgeBundle\Form\Handler\OfferHandler

    cb_form.type.panel_view_multiple_entity.class: CB\Bundle\NewAgeBundle\Form\Type\PanelViewMultipleEntityType

    cb_newage_reservation.form.type.entity.class:                      CB\Bundle\NewAgeBundle\Form\Type\ReservationType
    cb_newage_reservation.form.type.entity.api.class:                  CB\Bundle\NewAgeBundle\Form\Type\ReservationApiType
    cb_newage_reservation.form.handler.entity.class:                   CB\Bundle\NewAgeBundle\Form\Handler\ReservationHandler

services:
    cb_newage_panel.form.type.entity:
        class: %cb_newage_panel.form.type.entity.class%
        arguments:
            - @router
            - @oro_security.security_facade
        tags:
            - { name: form.type, alias: cb_newage_panel }

    cb_newage_panel.form.handler.entity:
        class: %cb_newage_panel.form.handler.entity.class%
        scope: request
        arguments:
            - @cb_newage_panel.form.entity
            - @request
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    cb_newage_panel.form.entity:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'cb_newage_panel_form'
            - 'cb_newage_panel'

    cb_newage_panel.form.type.entity.api:
        class: %cb_newage_panel.form.type.entity.api.class%
        tags:
            - { name: form.type, alias: cb_newage_panel_api }

    cb_newage_panel.form.handler.entity.api:
        class: %cb_newage_panel.form.handler.entity.class%
        scope: request
        arguments:
            - @cb_newage_panel.form.entity.api
            - @request
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    cb_newage_panel.form.entity.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'panel'
            - 'cb_newage_panel_api'

    cb_newage_panel_view.form.type.entity:
        class: %cb_newage_panel_view.form.type.entity.class%
        arguments:
            - @router
            - @oro_security.security_facade
        tags:
            - { name: form.type, alias: cb_newage_panel_view }

    cb_newage_panel_view.form.handler.entity:
        class: %cb_newage_panel_view.form.handler.entity.class%
        scope: request
        arguments:
            - @cb_newage_panel_view.form.entity
            - @request
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    cb_newage_panel_view.form.entity:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'cb_newage_panel_view_form'
            - 'cb_newage_panel_view'

    cb_newage_panel_view.form.type.entity.api:
        class: %cb_newage_panel_view.form.type.entity.api.class%
        tags:
            - { name: form.type, alias: cb_newage_panel_view_api }

    cb_newage_panel_view.form.handler.entity.api:
        class: %cb_newage_panel_view.form.handler.entity.class%
        scope: request
        arguments:
            - @cb_newage_panel_view.form.entity.api
            - @request
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    cb_newage_panel_view.form.entity.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'panel_view'
            - 'cb_newage_panel_view_api'

    cb_newage_campaign.form.type.entity:
        class: %cb_newage_campaign.form.type.entity.class%
        arguments:
            - @router
            - @oro_security.security_facade
        tags:
            - { name: form.type, alias: cb_newage_campaign }

    cb_newage_campaign.form.handler.entity:
        class: %cb_newage_campaign.form.handler.entity.class%
        scope: request
        arguments:
            - @cb_newage_campaign.form.entity
            - @request
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    cb_newage_campaign.form.entity:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'cb_newage_campaign_form'
            - 'cb_newage_campaign'

    cb_newage_campaign.form.type.entity.api:
        class: %cb_newage_campaign.form.type.entity.api.class%
        tags:
            - { name: form.type, alias: cb_newage_campaign_api }

    cb_newage_campaign.form.handler.entity.api:
        class: %cb_newage_campaign.form.handler.entity.class%
        scope: request
        arguments:
            - @cb_newage_campaign.form.entity.api
            - @request
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    cb_newage_campaign.form.entity.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'campaign'
            - 'cb_newage_campaign_api'

    cb_newage_support_type.form.type.entity:
        class: %cb_newage_support_type.form.type.entity.class%
        arguments:
            - @router
            - @oro_security.security_facade
        tags:
            - { name: form.type, alias: cb_newage_support_type }

    cb_newage_support_type.form.handler.entity:
        class: %cb_newage_support_type.form.handler.entity.class%
        scope: request
        arguments:
            - @cb_newage_support_type.form.entity
            - @request
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    cb_newage_support_type.form.entity:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'cb_newage_support_type_form'
            - 'cb_newage_support_type'

    cb_newage_support_type.form.type.entity.api:
        class: %cb_newage_support_type.form.type.entity.api.class%
        tags:
            - { name: form.type, alias: cb_newage_support_type_api }

    cb_newage_support_type.form.handler.entity.api:
        class: %cb_newage_support_type.form.handler.entity.class%
        scope: request
        arguments:
            - @cb_newage_support_type.form.entity.api
            - @request
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    cb_newage_support_type.form.entity.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'support_type'
            - 'cb_newage_support_type_api'

    cb_newage_lighting_type.form.type.entity:
        class: %cb_newage_lighting_type.form.type.entity.class%
        arguments:
            - @router
            - @oro_security.security_facade
        tags:
            - { name: form.type, alias: cb_newage_lighting_type }

    cb_newage_lighting_type.form.handler.entity:
        class: %cb_newage_lighting_type.form.handler.entity.class%
        scope: request
        arguments:
            - @cb_newage_lighting_type.form.entity
            - @request
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    cb_newage_lighting_type.form.entity:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'cb_newage_lighting_type_form'
            - 'cb_newage_lighting_type'

    cb_newage_lighting_type.form.type.entity.api:
        class: %cb_newage_lighting_type.form.type.entity.api.class%
        tags:
            - { name: form.type, alias: cb_newage_lighting_type_api }

    cb_newage_lighting_type.form.handler.entity.api:
        class: %cb_newage_lighting_type.form.handler.entity.class%
        scope: request
        arguments:
            - @cb_newage_lighting_type.form.entity.api
            - @request
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    cb_newage_lighting_type.form.entity.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'lighting_type'
            - 'cb_newage_lighting_type_api'

    cb_newage_panel_address_collection.form.type.entity:
        class: %cb_newage_panel_address_collection.form.type.entity.class%
        tags:
             - { name: form.type, alias: cb_panel_address_collection }

    cb_newage_city.form.type.entity:
        class: %cb_newage_city.form.type.entity.class%
        arguments:
            - @router
            - @oro_security.security_facade
        tags:
            - { name: form.type, alias: cb_newage_city }

    cb_newage_city.form.handler.entity:
        class: %cb_newage_city.form.handler.entity.class%
        scope: request
        arguments:
            - @cb_newage_city.form.entity
            - @request
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    cb_newage_city.form.entity:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'cb_newage_city_form'
            - 'cb_newage_city'

    cb_newage_city.form.type.entity.api:
        class: %cb_newage_city.form.type.entity.api.class%
        tags:
            - { name: form.type, alias: cb_newage_city_api }

    cb_newage_city.form.handler.entity.api:
        class: %cb_newage_city.form.handler.entity.class%
        scope: request
        arguments:
            - @cb_newage_city.form.entity.api
            - @request
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    cb_newage_city.form.entity.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'city'
            - 'cb_newage_city_api'

    cb_newage_offer.form.type.entity:
        class: %cb_newage_offer.form.type.entity.class%
        arguments:
            - @router
            - @oro_security.security_facade
        tags:
            - { name: form.type, alias: cb_newage_offer }

    cb_newage_offer.form.handler.entity:
        class: %cb_newage_offer.form.handler.entity.class%
        scope: request
        arguments:
            - @cb_newage_offer.form.entity
            - @request
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    cb_newage_offer.form.entity:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'cb_newage_offer_form'
            - 'cb_newage_offer'

    cb_newage_offer.form.type.entity.api:
        class: %cb_newage_offer.form.type.entity.api.class%
        tags:
            - { name: form.type, alias: cb_newage_offer_api }

    cb_newage_offer.form.handler.entity.api:
        class: %cb_newage_offer.form.handler.entity.class%
        scope: request
        arguments:
            - @cb_newage_offer.form.entity.api
            - @request
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    cb_newage_offer.form.entity.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'offer'
            - 'cb_newage_offer_api'

    cb_form.type.panel_view_multiple_entity:
        class: %cb_form.type.panel_view_multiple_entity.class%
        arguments:
            - '@router'
            - '@oro_entity.doctrine_helper'
            - '@oro_security.security_facade'
        tags:
            - { name: form.type, alias: cb_panel_view_multiple_entity }

    cb_newage_reservation.form.type.entity:
        class: %cb_newage_reservation.form.type.entity.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.security_facade
        tags:
            - { name: form.type, alias: cb_newage_reservation }

    cb_newage_reservation.form.handler.entity:
        class: %cb_newage_reservation.form.handler.entity.class%
        scope: request
        arguments:
            - @cb_newage_reservation.form.entity
            - @request
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    cb_newage_reservation.form.entity:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'cb_newage_reservation_form'
            - 'cb_newage_reservation'

    cb_newage_reservation.form.type.entity.api:
        class: %cb_newage_reservation.form.type.entity.api.class%
        tags:
            - { name: form.type, alias: cb_newage_reservation_api }

    cb_newage_reservation.form.handler.entity.api:
        class: %cb_newage_reservation.form.handler.entity.class%
        scope: request
        arguments:
            - @cb_newage_reservation.form.entity.api
            - @request
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    cb_newage_reservation.form.entity.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'reservation'
            - 'cb_newage_reservation_api'