parameters:
    cb_newage.mass_action.offer.class: CB\Bundle\NewAgeBundle\Extension\MassAction\Actions\OfferMassAction
    cb_newage.mass_action.offer_handler.class: CB\Bundle\NewAgeBundle\Extension\MassAction\OfferMassActionHandler

    cb_newage.mass_action.reserve.class: CB\Bundle\NewAgeBundle\Extension\MassAction\Actions\ReserveMassAction
    cb_newage.mass_action.reserve_handler.class: CB\Bundle\NewAgeBundle\Extension\MassAction\ReserveMassActionHandler

    cb_newage.mass_action.confirm.class: CB\Bundle\NewAgeBundle\Extension\MassAction\Actions\ConfirmMassAction
    cb_newage.mass_action.confirm_handler.class: CB\Bundle\NewAgeBundle\Extension\MassAction\ConfirmMassActionHandler

    cb_newage.mass_action.cancel.class: CB\Bundle\NewAgeBundle\Extension\MassAction\Actions\CancelMassAction
    cb_newage.mass_action.cancel_handler.class: CB\Bundle\NewAgeBundle\Extension\MassAction\CancelMassActionHandler

services:
    cb_newage.mass_action.offer:
        class: %cb_newage.mass_action.offer.class%
        arguments:
            - '@translator'
        scope: prototype
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: offer }


    cb_newage.mass_action.offer_handler:
        class: %cb_newage.mass_action.offer_handler.class%
        arguments:
            - '@doctrine.orm.entity_manager'

    cb_newage.mass_action.reserve:
        class: %cb_newage.mass_action.reserve.class%
        arguments:
            - '@translator'
        scope: prototype
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: reserve }

    cb_newage.mass_action.reserve_handler:
        class: %cb_newage.mass_action.reserve_handler.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@translator'
            - '@security.context'
            - '@oro_security.security_facade.link'
            - '@oro_email.email.manager'

    cb_newage.mass_action.confirm:
        class: %cb_newage.mass_action.confirm.class%
        arguments:
            - '@translator'
        scope: prototype
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: confirm }

    cb_newage.mass_action.confirm_handler:
        class: %cb_newage.mass_action.confirm_handler.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@translator'
            - '@security.context'
            - '@oro_security.security_facade.link'

    cb_newage.mass_action.cancel:
        class: %cb_newage.mass_action.cancel.class%
        arguments:
            - '@translator'
        scope: prototype
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: cancel }

    cb_newage.mass_action.cancel_handler:
        class: %cb_newage.mass_action.cancel_handler.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@translator'
            - '@security.context'
            - '@oro_security.security_facade.link'