oro_menu_config:
    items:
        newage_tab:
            label: 'cb.newage.menu.newage_tab.label'
            uri:   '#'
            extras:
                position: 1

        newage_tab_panel_link:
            label: 'cb.newage.menu.newage_tab_panel_link.label'
            route: cb_newage_panel_index
        newage_tab_panel_view_link:
            label: 'cb.newage.menu.newage_tab_panel_view_link.label'
            route: cb_newage_panel_view_index

    tree:
        application_menu:
            children:
                newage_tab:
                    children:
                        newage_tab_panel_link: ~
                        newage_tab_panel_view_link: ~
oro_titles:
    cb_newage_panel_index: ~
    cb_newage_panel_view: '%%entity.name%%'
    cb_newage_panel_create: 'oro.ui.create_entity'
    cb_newage_panel_update: '%%entity.name%% - oro.ui.edit'

    cb_newage_panel_view_index: ~
    cb_newage_panel_view_view: '%%entity.name%%'
    cb_newage_panel_view_create: 'oro.ui.create_entity'
    cb_newage_panel_view_update: '%%entity.name%% - oro.ui.edit'