oro_menu_config:
    items:
        customers_tab: ~
        sales_tab: ~
        activities_tab: ~
        marketing_tab: ~

        campaign_tab:
            label: 'cb.newage.campaign.entity_plural_label'
            route:   cb_newage_campaign_index
            extras:
                position: 2
        panel_view_tab:
            label: 'cb.newage.panelview.entity_plural_label'
            route:   cb_newage_panel_view_index
            extras:
                position: 3
        panel_tab:
            label: 'cb.newage.panel.entity_plural_label'
            route:   cb_newage_panel_index
            extras:
                position: 4

        newage_tab_panel_link:
            label: 'cb.newage.panel.entity_plural_label'
            route: cb_newage_panel_index
        newage_tab_panel_view_link:
            label: 'cb.newage.panelview.entity_plural_label'
            route: cb_newage_panel_view_index
        newage_tab_campaign_link:
            label: 'cb.newage.campaign.entity_plural_label'
            route: cb_newage_campaign_index

    tree:
        application_menu:
            children:
                campaign_tab: ~
                panel_view_tab: ~
                panel_tab: ~

oro_titles:
    cb_newage_panel_index: ~
    cb_newage_panel_view: '%%entity.name%%'
    cb_newage_panel_create: 'oro.ui.create_entity'
    cb_newage_panel_update: '%%entity.name%% - oro.ui.edit'

    cb_newage_panel_view_index: ~
    cb_newage_panel_view_view: '%%entity.name%%'
    cb_newage_panel_view_create: 'oro.ui.create_entity'
    cb_newage_panel_view_update: '%%entity.name%% - oro.ui.edit'

    cb_newage_campaign_index: ~
    cb_newage_campaign_view: '%%entity.name%%'
    cb_newage_campaign_create: 'oro.ui.create_entity'
    cb_newage_campaign_update: '%%entity.name%% - oro.ui.edit'
