
parameters:
    cb_newage_panel.entity.class:               CB\Bundle\NewAgeBundle\Entity\Panel
    cb_newage_panel.manager.class:              CB\Bundle\NewAgeBundle\Model\PanelManager
    cb_newage_panel.manager.api.class:          CB\Bundle\NewAgeBundle\Model\PanelApiManager

    cb_newage_panel_view.entity.class:               CB\Bundle\NewAgeBundle\Entity\PanelView
    cb_newage_panel_view.manager.class:              CB\Bundle\NewAgeBundle\Model\PanelViewManager
    cb_newage_panel_view.manager.api.class:          CB\Bundle\NewAgeBundle\Model\PanelViewApiManager

    cb_newage_campaign.entity.class:               CB\Bundle\NewAgeBundle\Entity\Campaign
    cb_newage_campaign.manager.class:              CB\Bundle\NewAgeBundle\Model\CampaignManager
    cb_newage_campaign.manager.api.class:          CB\Bundle\NewAgeBundle\Model\CampaignApiManager

    cb_newage_available.datasource.available.class:     CB\Bundle\NewAgeBundle\Extension\AvailableDatasource

    cb_newage_panel_address.entity.class:               CB\Bundle\NewAgeBundle\Entity\PanelAddress
    cb_newage_panel_address.manager.class:              CB\Bundle\NewAgeBundle\Model\PanelAddressManager
    cb_newage_panel_address.manager.api.class:          CB\Bundle\NewAgeBundle\Model\PanelAddressApiManager

    cb_newage.form.type.panel_address.class:            CB\Bundle\NewAgeBundle\Form\Type\PanelAddressType

    cb_newage_support_type.entity.class:               CB\Bundle\NewAgeBundle\Entity\SupportType
    cb_newage_support_type.manager.class:              CB\Bundle\NewAgeBundle\Model\SupportTypeManager
    cb_newage_support_type.manager.api.class:          CB\Bundle\NewAgeBundle\Model\SupportTypeApiManager

    cb_newage_lighting_type.entity.class:               CB\Bundle\NewAgeBundle\Entity\LightingType
    cb_newage_lighting_type.manager.class:              CB\Bundle\NewAgeBundle\Model\LightingTypeManager
    cb_newage_lighting_type.manager.api.class:          CB\Bundle\NewAgeBundle\Model\LightingTypeApiManager

services:
    cb_newage_panel.manager:
        class: %cb_newage_panel.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.acl_helper

    cb_newage_panel.manager.api:
        class: %cb_newage_panel.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %cb_newage_panel.entity.class%
            - @doctrine.orm.entity_manager
            - @cb_newage_panel.manager

    cb_newage_panel_view.manager:
        class: %cb_newage_panel_view.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.acl_helper

    cb_newage_panel_view.manager.api:
        class: %cb_newage_panel_view.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %cb_newage_panel_view.entity.class%
            - @doctrine.orm.entity_manager
            - @cb_newage_panel_view.manager

    cb_newage_campaign.manager:
        class: %cb_newage_campaign.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.acl_helper

    cb_newage_campaign.manager.api:
        class: %cb_newage_campaign.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %cb_newage_campaign.entity.class%
            - @doctrine.orm.entity_manager
            - @cb_newage_campaign.manager

    cb_newage_available.datasource.available:
        class: %cb_newage_available.datasource.available.class%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_datagrid.datasource, type: available }

    cb_newage_panel_address.manager:
        class: %cb_newage_panel_address.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.acl_helper

    cb_newage_panel_address.manager.api:
        class: %cb_newage_panel_address.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %cb_newage_panel_address.entity.class%
            - @doctrine.orm.entity_manager
            - @cb_newage_panel_address.manager

    cb_newage.form.type.panel_address:
        class: %cb_newage.form.type.panel_address.class%
        tags:
             - { name: form.type, alias: cb_panel_address }

    cb_newage.panel_address.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "cb_newage_panel_address_form"
            - "cb_panel_address"
            - ~
            - { data_class: %cb_newage_panel_address.entity.class% }

    cb_newage.form.handler.panel_address:
        class: %oro_address.form.handler.address.class%
        scope: request
        arguments:
            - "@cb_newage.panel_address.form"
            - "@request"
            - "@doctrine.orm.entity_manager"

    cb_newage_support_type.manager:
        class: %cb_newage_support_type.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.acl_helper

    cb_newage_support_type.manager.api:
        class: %cb_newage_support_type.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %cb_newage_support_type.entity.class%
            - @doctrine.orm.entity_manager
            - @cb_newage_support_type.manager

    cb_newage_lighting_type.manager:
        class: %cb_newage_lighting_type.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.acl_helper

    cb_newage_lighting_type.manager.api:
        class: %cb_newage_lighting_type.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %cb_newage_lighting_type.entity.class%
            - @doctrine.orm.entity_manager
            - @cb_newage_lighting_type.manager
