parameters:
    cb_newage_panel.entity.class:               CB\Bundle\NewAgeBundle\Entity\Panel
    cb_newage_panel.manager.class:              CB\Bundle\NewAgeBundle\Model\PanelManager
    cb_newage_panel.manager.api.class:          CB\Bundle\NewAgeBundle\Model\PanelApiManager

    cb_newage_panel_view.entity.class:               CB\Bundle\NewAgeBundle\Entity\PanelView
    cb_newage_panel_view.manager.class:              CB\Bundle\NewAgeBundle\Model\PanelViewManager
    cb_newage_panel_view.manager.api.class:          CB\Bundle\NewAgeBundle\Model\PanelViewApiManager

    cb_newage_client.entity.class:               CB\Bundle\NewAgeBundle\Entity\Client
    cb_newage_client.manager.class:              CB\Bundle\NewAgeBundle\Model\ClientManager
    cb_newage_client.manager.api.class:          CB\Bundle\NewAgeBundle\Model\ClientApiManager

    cb_newage_panel_address.entity.class:               CB\Bundle\NewAgeBundle\Entity\PanelAddress
    cb_newage_panel_address.manager.api.class:          Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    cb_newage_panel_address.form.handler.class:         CB\Bundle\NewAgeBundle\Form\Handler\PanelAddressHandler

    cb_newage.form.type.panel_address.class:            CB\Bundle\NewAgeBundle\Form\Type\PanelAddressType

    cb_newage_support_type.entity.class:               CB\Bundle\NewAgeBundle\Entity\SupportType
    cb_newage_support_type.manager.class:              CB\Bundle\NewAgeBundle\Model\SupportTypeManager
    cb_newage_support_type.manager.api.class:          CB\Bundle\NewAgeBundle\Model\SupportTypeApiManager

    cb_newage_lighting_type.entity.class:               CB\Bundle\NewAgeBundle\Entity\LightingType
    cb_newage_lighting_type.manager.class:              CB\Bundle\NewAgeBundle\Model\LightingTypeManager
    cb_newage_lighting_type.manager.api.class:          CB\Bundle\NewAgeBundle\Model\LightingTypeApiManager

    cb_newage_city.entity.class:               CB\Bundle\NewAgeBundle\Entity\City
    cb_newage_city.manager.class:              CB\Bundle\NewAgeBundle\Model\CityManager
    cb_newage_city.manager.api.class:          CB\Bundle\NewAgeBundle\Model\CityApiManager

    cb_newage.multiple_choice.datagrid_helper.class:    CB\Bundle\NewAgeBundle\Datagrid\MultipleChoiceGridHelper

    cb_newage_offer.entity.class:               CB\Bundle\NewAgeBundle\Entity\Offer
    cb_newage_offer.manager.class:              CB\Bundle\NewAgeBundle\Model\OfferManager
    cb_newage_offer.manager.api.class:          CB\Bundle\NewAgeBundle\Model\OfferApiManager

    cb_newage.subscriber.offer_listener.class: CB\Bundle\NewAgeBundle\EventListener\OfferListener
    cb_newage.subscriber.panel_listener.class: CB\Bundle\NewAgeBundle\EventListener\PanelListener

    cb_newage.offer_item.entity.class:               CB\Bundle\NewAgeBundle\Entity\OfferItem
    cb_newage.reservation-item.entity.class:         CB\Bundle\NewAgeBundle\Entity\ReservationItem

    cb_newage.mailer.processor.class:              CB\Bundle\NewAgeBundle\Mailer\Processor

services:
    cb_newage_panel.manager:
        class: %cb_newage_panel.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.acl_helper

    cb_newage_panel.manager.api:
        class: %cb_newage_panel.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %cb_newage_panel.entity.class%
            - @doctrine.orm.entity_manager
            - @cb_newage_panel.manager

    cb_newage_panel_view.manager:
        class: %cb_newage_panel_view.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.acl_helper

    cb_newage_panel_view.manager.api:
        class: %cb_newage_panel_view.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %cb_newage_panel_view.entity.class%
            - @doctrine.orm.entity_manager
            - @cb_newage_panel_view.manager

    cb_newage_client.manager:
        class: %cb_newage_client.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.acl_helper

    cb_newage_client.manager.api:
        class: %cb_newage_client.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %cb_newage_client.entity.class%
            - @doctrine.orm.entity_manager
            - @cb_newage_client.manager

    cb_newage_panel_address.manager.api:
        class: %cb_newage_panel_address.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %cb_newage_panel_address.entity.class%
            - @doctrine.orm.entity_manager

    cb_newage.form.type.panel_address:
        class: %cb_newage.form.type.panel_address.class%
        tags:
             - { name: form.type, alias: cb_panel_address }

    cb_newage.panel_address.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "cb_newage_panel_address_form"
            - "cb_panel_address"
            - ~
            - { data_class: %cb_newage_panel_address.entity.class% }

    cb_newage.form.handler.panel_address:
        class: %cb_newage_panel_address.form.handler.class%
        scope: request
        arguments:
            - "@cb_newage.panel_address.form"
            - "@request"
            - "@doctrine.orm.entity_manager"

    cb_newage_support_type.manager:
        class: %cb_newage_support_type.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.acl_helper

    cb_newage_support_type.manager.api:
        class: %cb_newage_support_type.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %cb_newage_support_type.entity.class%
            - @doctrine.orm.entity_manager
            - @cb_newage_support_type.manager

    cb_newage_lighting_type.manager:
        class: %cb_newage_lighting_type.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.acl_helper

    cb_newage_lighting_type.manager.api:
        class: %cb_newage_lighting_type.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %cb_newage_lighting_type.entity.class%
            - @doctrine.orm.entity_manager
            - @cb_newage_lighting_type.manager

    cb_newage_city.manager:
        class: %cb_newage_city.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.acl_helper

    cb_newage_city.manager.api:
        class: %cb_newage_city.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %cb_newage_city.entity.class%
            - @doctrine.orm.entity_manager
            - @cb_newage_city.manager

    cb_newage_offer.manager:
        class: %cb_newage_offer.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.acl_helper

    cb_newage_offer.manager.api:
        class: %cb_newage_offer.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %cb_newage_offer.entity.class%
            - @doctrine.orm.entity_manager
            - @cb_newage_offer.manager

    cb_newage.subscriber.offer_listener:
        class: %cb_newage.subscriber.offer_listener.class%
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    cb_newage.subscriber.panel_listener:
        class: %cb_newage.subscriber.panel_listener.class%
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    cb_newage.mailer.processor:
        class: %cb_newage.mailer.processor.class%
        arguments:
            - @templating
            - @oro_config.global
            - @oro_email.direct_mailer

    cb_newage.multiple_choice.datagrid_helper:
        class: %cb_newage.multiple_choice.datagrid_helper.class%
        arguments:
            - '@doctrine'
            - '@oro_security.acl_helper'
            - '@translator'

    cb_datagrid.handler.export:
        class: CB\Bundle\NewAgeBundle\Datagrid\ExportHandler
        arguments:
            - '@oro_importexport.file.file_system_operator'
        calls:
            - [setLogger, ['@logger']]

    cb_newage.repository.panel_view:
        class: 'CB\Bundle\NewAgeBundle\Entity\Repository\PanelViewRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - '%cb_newage_panel_view.entity.class%'
        calls:
            - [ setRequestStack, [ '@request_stack' ] ]