CB\Bundle\NewAgeBundle\Entity\Panel:
    properties:
        name:
            - Length:
                min:        3
                max:        255
        supportType:
            - NotBlank: ~
        lightingType:
            - NotBlank: ~
CB\Bundle\NewAgeBundle\Entity\PanelAddress:
    properties:
        latitude:
            - NotBlank: ~
        longitude:
            - NotBlank: ~
CB\Bundle\NewAgeBundle\Entity\Offer:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min:    3
                max:    255
        start:
            - Date: ~
            - GreaterThanOrEqual:
                value: today
                message: Start date should be greater or equal than current date
        end:
            - Date: ~
            - Expression:
                expression: "this.isGreaterThanStart(7)"
                message: End date should be greater with 5 days than start date
