datagrids:
    base-scheduler_event-grid:
        source:
            type: orm
            acl_resource: cb_scheduler_event_view
            query:
                select:
                    - se.id
                    - se.start
                    - se.end
                    - se.status
                    - pv.name as panelView
                    - c.title as client
                    - p.name as panel
                    - st.name as supportType
                    - lt.name as lightingType
                    - ct.name as city
#                    - o.name as offer
                from:
                    - { table: %cb_scheduler.scheduler_event.entity.class%, alias: se }
                join:
                    left:
                        -
                            join: se.panelView
                            alias: pv
                        -
                            join: se.client
                            alias: c
                        -
                            join: pv.panel
                            alias: p
                        -
                            join: p.supportType
                            alias: st
                        -
                            join: p.lightingType
                            alias: lt
                        - { join: p.addresses, alias: addr, conditionType: WITH, condition: 'addr.primary = true' }
                        -
                            join: addr.city
                            alias: ct

        columns:
            start:
                label:  cb.scheduler.scheduler_event.start.label
                frontend_type: date
            end:
                label:  cb.scheduler.scheduler_event.end.label
                frontend_type: date
            status:
                label:  cb.scheduler.scheduler_event.status.label
                type:          twig
                frontend_type: html
                template:      CBNewAgeBundle:Datagrid:Property/available.html.twig

            panel:
                label:  cb.newage.panel.entity_label
            panelView:
                label:  cb.newage.panelview.entity_label
            client:
                label:  cb.newage.client.entity_label
            supportType:
                label:  cb.newage.supporttype.entity_label
            lightingType:
                label:  cb.newage.lightingtype.entity_label
            city:
                label:  oro.address.city.label
        sorters:
              columns:
                  start:
                      data_name: se.start
                  client:
                      data_name: c.title
              default:
                  start:  '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC'

        properties:
            id: ~
            view_link:
                type:         url
                route:        cb_scheduler_scheduler_event_view
                params:       [ id ]
            update_link:
                type:         url
                route:        cb_scheduler_scheduler_event_update
                params:       [ id ]
            delete_link:
                type:         url
                route:        cb_api_delete_schedulerevent
                params:       [ id ]
        actions:
            view:
                type:         navigate
                acl_resource: cb_newage_panel_view
                label:        oro.grid.action.view
                icon:         eye-open
                link:         view_link
                rowAction:    true
            update:
                type:         navigate
                acl_resource: cb_newage_panel_update
                label:        oro.grid.action.update
                icon:         edit
                link:         update_link
            delete:
                type:         delete
                acl_resource: cb_newage_panel_delete
                label:        oro.grid.action.delete
                icon:         trash
                link:         delete_link
        action_configuration:
#            delete: false

    scheduler-grid:
        extends: base-scheduler_event-grid
        filters:
            columns:
                status:
                    type:        choice
                    data_name:   se.status
                    options:
                        field_options:
                            choices:
                                1: Reserved
                                2: Confirmed
                client:
                    type: entity
                    data_name: se.client
                    options:
                        field_options:
                            class: CBNewAgeBundle:Client
                city:
                    type:      choice
                    data_name: addr.city
                    null_value: _empty_
                    options:
                        field_options:
                            multiple:       true
                            choices:        @cb_newage.multiple_choice.datagrid_helper->getValues(%cb_newage_city.entity.class%)
                            translatable_options: false
                panel:
                    type: entity
                    data_name: pv.panel
                    options:
                        field_options:
                            class: CBNewAgeBundle:Panel
                    enabled: false
                panelView:
                    type: entity
                    data_name: se.panelView
                    options:
                        field_options:
                            class: CBNewAgeBundle:PanelView
                    enabled: false
                supportType:
                    type:      choice
                    label:  cb.newage.supporttype.entity_label
                    data_name: p.supportType
                    null_value: _empty_
                    options:
                        field_options:
                            multiple:       true
                            choices:        @cb_newage.multiple_choice.datagrid_helper->getValues(%cb_newage_support_type.entity.class%)
                            translatable_options: false
                lightingType:
                    type:      choice
                    label:  cb.newage.lightingtype.entity_label
                    data_name: p.lightingType
                    null_value: _empty_
                    options:
                        field_options:
                            multiple:       true
                            choices:        @cb_newage.multiple_choice.datagrid_helper->getValues(%cb_newage_lighting_type.entity.class%)
                            translatable_options: false
    scheduler_event-grid:
        extends: scheduler-grid
        filters:
            columns:
                start:
                    type:        datetime
                    data_name:   se.start
                end:
                    type:        datetime
                    data_name:   se.end

#            default:
#                status:
#                    value: 2

        options:
            mass_actions:
                delete:
                    enabled: false
            routerEnabled: false

    # Campaing view
    client-scheduler_event-grid:
        extends: base-scheduler_event-grid
        source:
            query:
                where:
                    and:
                        - ( se.client = :client_id)
            bind_parameters:
                - client_id