imports:
    - { resource: 'offer/steps.yml' }
    - { resource: 'offer/attributes.yml' }
    - { resource: 'offer/transitions.yml' }
    - { resource: 'offer/transition_definitions.yml' }

workflows:
    offer:
        label: 'Create new offer'
        entity: CB\Bundle\NewAgeBundle\Entity\Offer
        entity_attribute: offer