workflows:
    offer:
        attributes:
            offer_name:
                property_path: offer.name
            offer_start:
                property_path: offer.start
            offer_end:
                property_path: offer.end
            offer_campaign:
                property_path: offer.campaign
            panelViews:
                label: 'Panel Views'
                property_path: offer.panelViews
