workflows:
    offer:
        steps:
            started:
                label: 'Initiated'
                order: 10
                allowed_transitions:
                    - create
                    - generate

            generated:
                label: 'Generated'
                order: 20
                allowed_transitions:
                    - generate
                    - filters

            filtered:
                label: 'Filtered'
                order: 20
                allowed_transitions:
                    - filters
                    - close

            closed:
                label: 'Finished'
                order: 30
                is_final: true