workflows:
    offer:
        transitions:
            create:
                label: 'Create offer'
                step_to: started
                is_start: true
                is_hidden: false
                is_unavailable_hidden: false
                acl_resource: cb_newage_offer_create
                display_type: page
                frontend_options:
                    icon: 'icon-edit'
                    class: 'btn-primary'
                    page:
                        parent_route: 'cb_newage_offer_index'
                        parent_label: cb.newage.offer.entity_plural_label
                form_options:
                    attribute_fields:
                        offer_name:
                            form_type: text
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        offer_start:
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        offer_end:
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        offer_campaign:
                            form_type: entity
                            options:
                                required: true
                                class: CB\Bundle\NewAgeBundle\Entity\Campaign
                                constraints:
                                  - NotBlank: ~
                    init_actions:
                        - @create_date:
                            attribute: $offer_start
                        - @create_date:
                            attribute: $offer_end
                transition_definition: create_definition

            filters:
                label: 'Select panel views'
                step_to: filtered
                is_unavailable_hidden: false
                acl_resource: cb_newage_offer_update
                display_type: page
                frontend_options:
                    icon: 'icon-filter'
                    class: 'btn-success'
                    page:
                        parent_route: 'cb_newage_offer_index'
                        parent_label: cb.newage.offer.entity_plural_label
                form_options:
                    attribute_fields:
                        panelViews:
                            form_type: cb_panel_view_multiple_entity
                            options:
                                required: true
                                class: 'CBNewAgeBundle:PanelView'
                                add_acl_resource: 'cb_newage_panel_view_view'
                                selector_window_title: 'cb.newage.offer.form.select_panel_views'
                                selection_route: 'cb_offer_widget_panel_views_info'
                                selection_route_parameters:
                                    id: $offer.id
#                                constraints:
#                                    - NotBlank: ~
                transition_definition: filters_definition

            close:
                label: 'Close'
                step_to: closed
                is_unavailable_hidden: false
                frontend_options:
                    icon: 'icon-ok'
                transition_definition: closed_definition
