workflows:
    offer:
        transition_definitions:
            create_definition:
                post_actions:
                    - @create_related_entity: # create Offer if it not exist yet
                        conditions:
                            @empty: [$offer.id]
                        parameters: ~
                    - @generate_offer_items:
                        parameters:
                            offer: $offer
                            attribute: $offer.items
                    - @redirect: # redirect to Offer view page
                        route: 'cb_newage_offer_view'
                        route_parameters:
                            id: $offer.id
                            workflow: true
            generate_definition:
                post_actions:
                    - @redirect: # redirect to Offer view page
                        route: 'cb_newage_offer_view'
                        route_parameters:
                            id: $offer.id
            filters_definition:
                post_actions:
                    - @tree:
                        - actions:
                            - @call_method:
                                object: $offer
                                method: setPanelViews
                                method_parameters: $offer.panelViews
                    - @redirect: # redirect to Offer view page
                        route: 'cb_newage_offer_view'
                        route_parameters:
                            id: $offer.id
            closed_definition: ~
