datagrid:
    base-scheduler_event-grid:
        source:
            type: orm
            acl_resource: cb_scheduler_event_view
            query:
                select:
                    - se.id
                    - se.start
                    - se.end
                    - se.status
                    - pv.name as panelView
                    - c.title as campaign
                    - p.name as panel
                    - st.name as supportType
                    - lt.name as lightingType
                    - ct.name as city
                from:
                    - { table: %cb_scheduler.scheduler_event.entity.class%, alias: se }
                join:
                    left:
                        -
                            join: se.panelView
                            alias: pv
                        -
                            join: se.campaign
                            alias: c
                        -
                            join: pv.panel
                            alias: p
                        -
                            join: p.supportType
                            alias: st
                        -
                            join: p.lightingType
                            alias: lt
                        - { join: p.addresses, alias: addr, conditionType: WITH, condition: 'addr.primary = true' }
                        -
                            join: addr.city
                            alias: ct
        columns:
            id:
                label:  cb.scheduler.scheduler_event.id.label
            start:
                label:  cb.scheduler.scheduler_event.start.label
                frontend_type: date
            end:
                label:  cb.scheduler.scheduler_event.end.label
                frontend_type: date
            status:
                label:  cb.scheduler.scheduler_event.status.label
            panel:
                label:  cb.newage.panel.entity_label
            panelView:
                label:  cb.newage.panelview.entity_label
            campaign:
                label:  cb.newage.campaign.entity_label
            supportType:
                label:  cb.newage.supporttype.entity_label
            lightingType:
                label:  cb.newage.lightingtype.entity_label
            city:
                label:  oro.address.city.label
        sorters:
            columns:
        properties:
            id: ~
        action_configuration:
            delete: false

    scheduler_event-grid:
        extends: base-scheduler_event-grid
        filters:
            columns:
                panel:
                    type: entity
                    data_name: pv.panel
                    options:
                        field_options:
                            class: CBNewAgeBundle:Panel
                panelView:
                    type: entity
                    data_name: se.panelView
                    options:
                        field_options:
                            class: CBNewAgeBundle:PanelView
                campaign:
                    type: entity
                    data_name: se.campaign
                    options:
                        field_options:
                            class: CBNewAgeBundle:Campaign
                supportType:
                    type: entity
                    data_name: st.name
                    options:
                        field_options:
                            class: CBNewAgeBundle:SupportType
                lightingType:
                    type: entity
                    data_name: lt.name
                    options:
                        field_options:
                            class: CBNewAgeBundle:LightingType
                city:
                    type: choice-tree
                    data_name: addr.city
                    options:
                        lazy: "@cb_city.provider.filter.city_choice_tree->shouldBeLazy"
                        data: "@?cb_city.provider.filter.city_choice_tree->getList"
                    enabled: true

    # Campaing view
    campaign-scheduler_event-grid:
        extends: base-scheduler_event-grid
        source:
            query:
                where:
                    and:
                        - ( se.campaign = :campaign_id)
            bind_parameters:
                - campaign_id