parameters:
    cb_scheduler.scheduler_event.form.type.class:           CB\Bundle\SchedulerBundle\Form\Type\SchedulerEventType
    cb_scheduler.scheduler_event.form.type.api.class:       CB\Bundle\SchedulerBundle\Form\Type\SchedulerEventApiType
    cb_scheduler.scheduler_event.form.handler.class:        CB\Bundle\SchedulerBundle\Form\Handler\SchedulerEventHandler
    cb_scheduler.scheduler_event.form.handler.api.class:    CB\Bundle\SchedulerBundle\Form\Handler\SchedulerEventApiHandler
    cb_scheduler.campaign_choice.form.type.class:           CB\Bundle\SchedulerBundle\Form\Type\CampaignChoiceType
    cb_scheduler.panel_view_choice.form.type.class:         CB\Bundle\SchedulerBundle\Form\Type\PanelViewChoiceType
    cb_scheduler.status_choice.form.type.class:             CB\Bundle\SchedulerBundle\Form\Type\StatusChoiceType

services:
    cb_scheduler.scheduler.form.type:
        class: %cb_scheduler.scheduler_event.form.type.class%
        tags:
            - { name: form.type, alias: cb_scheduler_event }

    cb_scheduler.scheduler_event.form.type.api:
        class: %cb_scheduler.scheduler_event.form.type.api.class%
        arguments:
            - '@cb_scheduler.scheduler_event.manager'
        tags:
            - { name: form.type, alias: cb_scheduler_event_api }

    cb_scheduler.scheduler_event.form.handler:
        class: "%cb_scheduler.scheduler_event.form.handler.class%"
        scope: request
        arguments:
            - "@cb_scheduler.scheduler_event.form"
            - "@request"
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"

    cb_scheduler.scheduler_event.form:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "cb_scheduler_event_form"
            - "cb_scheduler_event"

    cb_scheduler.scheduler_event.form.handler.api:
        class: %cb_scheduler.scheduler_event.form.handler.api.class%
        scope: request
        arguments:
            - @cb_scheduler.scheduler_event.form.api
            - @request
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    cb_scheduler.scheduler_event.form.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - ~
            - 'cb_scheduler_event_api'

    cb_scheduler.campaign_choice.form.type:
        class: %cb_scheduler.campaign_choice.form.type.class%
        arguments:
            - '@cb_scheduler.scheduler_event.manager'
            - '@translator'
        tags:
            - { name: form.type, alias: cb_campaign_choice }

    cb_scheduler.panel_view_choice.form.type:
        class: %cb_scheduler.panel_view_choice.form.type.class%
        arguments:
            - '@cb_scheduler.scheduler_event.manager'
            - '@translator'
        tags:
            - { name: form.type, alias: cb_panel_view_choice }

    cb_scheduler.status_choice.form.type:
        class: %cb_scheduler.status_choice.form.type.class%
        arguments:
            - '@oro_security.security_facade'
            - '@translator'
        tags:
            - { name: form.type, alias: cb_status_choice }
