config:
    map:
        '*':
            'orofilter/js/filters-manager': 'cbscheduler/js/filters-manager'
        'cbscheduler/js/filters-manager':
            'orofilter/js/filters-manager': 'bundles/orofilter/js/filters-manager.js'
    paths:
        'jquery':  'bundles/cbscheduler/lib/fullcalendar-scheduler/lib/jquery.min.js'
        'fullcalendar':  'bundles/cbscheduler/lib/fullcalendar-scheduler/lib/fullcalendar.min.js'
        'fullscheduler':  'bundles/cbscheduler/lib/fullcalendar-scheduler/scheduler.min.js'
        'cbscheduler/js/scheduler-view': 'bundles/cbscheduler/js/scheduler-view.js'
        'cbscheduler/js/scheduler/event/collection': 'bundles/cbscheduler/js/scheduler/event/collection.js'
        'cbscheduler/js/scheduler/event/model': 'bundles/cbscheduler/js/scheduler/event/model.js'
        'cbscheduler/js/scheduler/event/view': 'bundles/cbscheduler/js/scheduler/event/view.js'
        'cbscheduler/js/scheduler/panelView/collection': 'bundles/cbscheduler/js/scheduler/panelView/collection.js'
        'cbscheduler/js/scheduler/panelView/model': 'bundles/cbscheduler/js/scheduler/panelView/model.js'
        'cbscheduler/js/scheduler/campaign/collection': 'bundles/cbscheduler/js/scheduler/campaign/collection.js'
        'cbscheduler/js/scheduler/campaign/model': 'bundles/cbscheduler/js/scheduler/campaign/model.js'
        'cbscheduler/js/app/components/scheduler-component': 'bundles/cbscheduler/js/app/components/scheduler-component.js'
        'cbscheduler/js/app/modules/scheduler-module': 'bundles/cbscheduler/js/app/modules/scheduler-module.js'
        'cbscheduler/js/validator/dateearlierthan': 'bundles/cbscheduler/js/validator/dateearlierthan.js'
    appmodules:
        - cbscheduler/js/app/modules/scheduler-module