parameters:
    cb_scheduler.scheduler_event.entity.class:                    CB\Bundle\SchedulerBundle\Entity\SchedulerEvent
    cb_scheduler.scheduler_event.manager.class:                   CB\Bundle\SchedulerBundle\Manager\SchedulerEventManager
    cb_scheduler.scheduler_event.manager.api.class:               Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

services:
    cb_scheduler.scheduler_event.manager:
        class: "%cb_scheduler.scheduler_event.manager.class%"
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_security.security_facade'
            - '@oro_entity.entity_name_resolver'
            - '@oro_calendar.system_calendar_config'


    cb_scheduler.scheduler_event.manager.api:
        class: %cb_scheduler.scheduler_event.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %cb_scheduler.scheduler_event.entity.class%
            - @doctrine.orm.entity_manager