CB\Bundle\SchedulerBundle\Entity\SchedulerEvent:
    properties:
        start:
            - Date:     ~
            - NotBlank:     ~
            - Oro\Bundle\CalendarBundle\Validator\Constraints\DateEarlierThan: end
        end:
            - Date:     ~
            - NotBlank:     ~